### ISSUE TITLE
Glimmer error

### ISSUE THREAD

**Issue by ghoshal** [davek44/Glimmer-MG#2]
Hi,

Whenever I run glimmer-mg.py, I am getting this error

Scanning query lengths...done.  [Sat Oct 31 14:21:10 PDT 2015]

Reading IMM list...done.  [Sat Oct 31 14:21:10 PDT 2015]

Creating reverse complement of seqs_240471.fa...done.  [Sat Oct 31 14:21:10 PDT 2015]

Loading taxonomy...done.  [Sat Oct 31 14:21:10 PDT 2015]

Scoring reads with Phymm...rm: cannot remove `tempFwd_seqs_240471_fa.txt': No such file or directory
rm: cannot remove `tempRev_seqs_240471_fa.txt': No such file or directory
rm: cannot remove `errFile_seqs_240471_fa.txt': No such file or directory
done.  [Sat Oct 31 14:21:12 PDT 2015]

Traceback (most recent call last):
  File "/home/biba/data/glimmer-mg/scripts/glimmer-mg.py", line 699, in <module>
    main()
  File "/home/biba/data/glimmer-mg/scripts/glimmer-mg.py", line 51, in main
    (sequence_classes,sequence_scores) = parse_phymm(sequence_file, options.top_hits, options.ignore)
  File "/home/biba/data/glimmer-mg/scripts/glimmer-mg.py", line 599, in parse_phymm
    sequence_top_scores[seq] = sequence_scores[s][0][0]
IndexError: string index out of range

Please help.

Thanks,

Bibaswan

**Comment by davek44** [comment]
NCBI appears to have changed the URL used by Phymm to grab the bacterial taxonomy. If you replace .scripts/.taxonomyInfo/0_getNCBIpages.pl with the one that I just committed into the directory _phymm_patch_, it should work again. I modified the install script, too. Try reinstalling phymm, and then testing Glimmer.
