### ISSUE TITLE
No taxonomy data or raw Phymm output

### ISSUE THREAD

**Issue by gputzel** [davek44/Glimmer-MG#3]
I installed the latest version (cloned the repo 6/30/17) and tried to run the sample. I get this:

```

>scripts/glimmer-mg.py sample-run/glimmer-mg/seqs.fa

Scanning query lengths...done.  [Fri Jun 30 13:29:09 EDT 2017]

Reading IMM list...done.  [Fri Jun 30 13:29:09 EDT 2017]

Creating reverse complement of seqs_66694.fa...done.  [Fri Jun 30 13:29:10 EDT 2017]

Loading taxonomy...Can't open .taxonomyData/.0_accessionMap/accessionMap.txt for reading.
Traceback (most recent call last):
  File "/home/greg/programs/glimmer-mg/scripts/phymm_par.py", line 507, in <module>
    main()
  File "/home/greg/programs/glimmer-mg/scripts/phymm_par.py", line 61, in main
    combine_imm(seqsf, pids, origdir)
  File "/home/greg/programs/glimmer-mg/scripts/phymm_par.py", line 425, in combine_imm
    raw_files.append(open('rawPhymmOutput_seqs_%d_fa.txt' % pid))
IOError: [Errno 2] No such file or directory: 'rawPhymmOutput_seqs_66694_fa.txt'
Cannot find raw Phymm output file rawPhymmOutput_seqs_fa.txt
```

I am running this on Ubuntu 16

**Comment by marcomarconi** [comment]
same error here

**Comment by davek44** [comment]
You could try installing Phymm with my substitute script here: https://github.com/davek44/Glimmer-MG/blob/master/phymm_patch/0_getNCBIpages.pl

More broadly, this software never really took off. Soon after writing it, I changed fields, so it never received the nurturing it would've needed to flourish. At this point, I'd be surprised if it were the best tool available.
